# Generated by Django 2.1.3 on 2018-11-23 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('user_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='user_reg',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='date_reg',
            new_name='blog_date',
        ),
        migrations.AddField(
            model_name='post',
            name='cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Category'),
            preserve_default=False,
        ),
    ]
