# Generated by Django 2.1.3 on 2018-11-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181122_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUB', 'Published'), ('EDIT', 'In edit')], default=0, max_length=3),
            preserve_default=False,
        ),
    ]
